CREATE TABLE all_time_leaders(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id integer NOT NULL,
    player_name text NOT NULL,
    stat_value numeric NOT NULL,
    stat_rank integer NOT NULL,
    stat_category text NOT NULL,
    UNIQUE (player_id, stat_category)
);

-- Add indexes for better query performance
CREATE INDEX idx_all_time_leaders_player_id ON all_time_leaders(player_id);

CREATE INDEX idx_all_time_leaders_stat_category ON all_time_leaders(stat_category);

