CREATE TABLE player_career_stats(
    player_id integer PRIMARY KEY,
    league_id varchar,
    gp integer,
    gs integer,
    min float,
    fgm integer,
    fga integer,
    fg_pct float,
    fg3m integer,
    fg3a integer,
    fg3_pct float,
    ftm integer,
    fta integer,
    ft_pct float,
    oreb integer,
    dreb integer,
    reb integer,
    ast integer,
    stl integer,
    blk integer,
    tov integer,
    pf integer,
    pts integer
);

