CREATE TABLE public.puzzles(
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  puzzle_id integer NOT NULL,
  date timestamp with time zone NOT NULL,
  GROUPS jsonb NOT NULL,
  author text NOT NULL,
  todays_theme text NOT NULL,
  CONSTRAINT puzzles_pkey PRIMARY KEY (id),
  CONSTRAINT puzzles_date_key UNIQUE (date)
)
TABLESPACE pg_default;

