CREATE TABLE season_totals_regular_season(
    player_id integer,
    season_id varchar(7),
    league_id varchar(3),
    team_id integer,
    team_abbreviation varchar(3),
    player_age integer,
    gp integer,
    gs integer,
    min numeric,
    fgm integer,
    fga integer,
    fg_pct numeric,
    fg3m integer,
    fg3a integer,
    fg3_pct numeric,
    ftm integer,
    fta integer,
    ft_pct numeric,
    oreb integer,
    dreb integer,
    reb integer,
    ast integer,
    stl integer,
    blk integer,
    tov integer,
    pf integer,
    pts integer,
    PRIMARY KEY (player_id, season_id)
);

