CREATE TABLE
  public.themes (
    theme_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    theme TEXT NOT NULL,
    color TEXT NOT NULL,
    emoji TEXT NOT NULL,
    words jsonb NOT NULL,
    used_in_puzzle BOOLEAN DEFAULT false,
    validated_state BOOLEAN DEFAULT false,
    CONSTRAINT themes_pkey PRIMARY KEY (theme_id)
  ) TABLESPACE pg_default;

-- Add index for commonly queried columns
CREATE INDEX themes_color_idx ON public.themes(color);
CREATE INDEX themes_used_puzzle_idx ON public.themes(used_in_puzzle);